-- TODO: Manual translation required. Original postgres SQL:
-- -- ============================================================
-- -- DM Generated Schema
-- -- Source: contacts
-- -- Tables: 3
-- -- Confidence: 0.8
-- -- Generated: 2026-04-28T20:54:26.270257+00:00
-- -- ============================================================
-- 
-- -- Generated by DM Schema Generator
-- -- Source: contacts (primary)
-- -- Generated: 2026-04-28T20:54:26.270260+00:00
-- 
-- CREATE TABLE ct_records (
--     ct_record_id              SERIAL PRIMARY KEY  -- Primary key for ct_records,
--     first_name                CHAR  -- Source: ct_fnam — CONTACT-FIRST-NAME,
--     middle_name               CHAR  -- Source: ct_mnam — CONTACT-MIDDLE-NAME,
--     last_name                 CHAR  -- Source: ct_lnam — CONTACT-LAST-NAME,
--     name_suffix               CHAR  -- Source: ct_sufx — CONTACT-NAME-SUFFIX,
--     ssn_hash                  VARCHAR(64)  -- Source: ct_ssn (SHA-256) PII: hash — CONTACT-SSN,
--     date_of_birth             CHAR  -- Source: ct_dob — CONTACT-DATE-OF-BIRTH,
--     gender                    CHAR  -- Source: ct_gndr — CONTACT-GENDER-CODE,
--     ethnicity                 CHAR  -- Source: ct_ethn — CONTACT-ETHNICITY,
--     address_type              CHAR  -- Source: ct_adtyp — CONTACT-ADDR-TYPE,
--     emergency_contact_name    VARCHAR  -- Source: ct_emrg — CONTACT-EMERGENCY-NAME,
--     emergency_contact_relation CHAR  -- Source: ct_erel — CONTACT-EMERGENCY-RELATION,
--     drivers_license_number    CHAR  -- Source: ct_dln — CONTACT-DRIVERS-LICENSE-NUM,
--     dependents_count          INTEGER  -- Source: ct_dpnds — CONTACT-DEPENDENTS-COUNT,
--     language_preference       CHAR  -- Source: ct_lang — CONTACT-LANGUAGE-PREF,
--     is_veteran                CHAR  -- Source: ct_vetf — CONTACT-VETERAN-FLAG,
--     is_disabled               CHAR  -- Source: ct_disf — CONTACT-DISABILITY-FLAG,
--     created_at                CHAR  -- Source: ct_crtdt — CONTACT-CREATED-DATE,
--     updated_at                CHAR  -- Source: ct_upddt — CONTACT-UPDATED-DATE,
--     source_code               CHAR  -- Source: ct_srccd — CONTACT-SOURCE-CODE,
--     fil1                      CHAR  -- Source: ct_fil1 — FILLER-1,
--     fil2                      CHAR  -- Source: ct_fil2 — FILLER-2,
--     created_at                TIMESTAMPTZ DEFAULT NOW(),
--     updated_at                TIMESTAMPTZ DEFAULT NOW()
-- )

CREATE INDEX idx_ct_records_ssn_hash ON ct_records(ssn_hash)

COMMENT ON TABLE ct_records IS 'Migrated from legacy contacts table. Role: primary. Primary entity from ct_ columns (confidence: 0.90)'

-- TODO: Manual translation required. Original postgres SQL:
-- -- Generated by DM Schema Generator
-- -- Source: contacts (child)
-- -- Generated: 2026-04-28T20:54:26.270269+00:00
-- 
-- CREATE TABLE ct_record_addresses (
--     ct_record_addresse_id     SERIAL PRIMARY KEY,
--     ct_record_id              INTEGER,
--     address_line1             VARCHAR  -- Source: ct_adr1 — CONTACT-STREET-ADDR-1,
--     address_line2             VARCHAR  -- Source: ct_adr2 — CONTACT-STREET-ADDR-2,
--     city                      CHAR  -- Source: ct_city — CONTACT-CITY-NAME,
--     state                     CHAR  -- Source: ct_st — CONTACT-STATE-CODE,
--     zip_code                  CHAR  -- Source: ct_zip — CONTACT-ZIP-CODE,
--     mailing_address_line1     VARCHAR  -- Source: ct_madr1 — CONTACT-MAIL-ADDR-1,
--     mailing_address_line2     VARCHAR  -- Source: ct_madr2 — CONTACT-MAIL-ADDR-2,
--     mailing_city              CHAR  -- Source: ct_mcity — CONTACT-MAIL-CITY,
--     mailing_state             CHAR  -- Source: ct_mst — CONTACT-MAIL-STATE,
--     mailing_zip_code          CHAR  -- Source: ct_mzip — CONTACT-MAIL-ZIP,
--     drivers_license_state     CHAR  -- Source: ct_dlst — CONTACT-DL-STATE,
--     marital_status            CHAR  -- Source: ct_mstat — CONTACT-MARITAL-STATUS,
--     marital_status            CHAR  -- Source: ct_stat — CONTACT-STATUS-CODE,
--     created_at                TIMESTAMPTZ DEFAULT NOW(),
--     updated_at                TIMESTAMPTZ DEFAULT NOW(),
--     CONSTRAINT fk_ct_record_addresses_ct_record_id FOREIGN KEY (ct_record_id) REFERENCES ct_records(ct_recid)
-- )

CREATE INDEX idx_ct_record_addresses_ct_record_id ON ct_record_addresses(ct_record_id)

COMMENT ON TABLE ct_record_addresses IS 'Migrated from legacy contacts table. Role: child. Child entity from ct_ columns (confidence: 0.80)'

-- TODO: Manual translation required. Original postgres SQL:
-- -- Generated by DM Schema Generator
-- -- Source: contacts (child)
-- -- Generated: 2026-04-28T20:54:26.270275+00:00
-- 
-- CREATE TABLE ct_record_contacts (
--     ct_record_contact_id      SERIAL PRIMARY KEY,
--     ct_record_id              INTEGER,
--     primary_phone             CHAR  -- Source: ct_ptel — CONTACT-PRIMARY-PHONE,
--     mobile_phone              CHAR  -- Source: ct_mtel — CONTACT-MOBILE-PHONE,
--     work_phone                CHAR  -- Source: ct_wtel — CONTACT-WORK-PHONE,
--     email                     VARCHAR  -- Source: ct_emal — CONTACT-EMAIL-ADDR,
--     emergency_contact_phone   CHAR  -- Source: ct_etel — CONTACT-EMERGENCY-PHONE,
--     created_at                TIMESTAMPTZ DEFAULT NOW(),
--     updated_at                TIMESTAMPTZ DEFAULT NOW(),
--     CONSTRAINT fk_ct_record_contacts_ct_record_id FOREIGN KEY (ct_record_id) REFERENCES ct_records(ct_recid)
-- )

CREATE INDEX idx_ct_record_contacts_ct_record_id ON ct_record_contacts(ct_record_id)

COMMENT ON TABLE ct_record_contacts IS 'Migrated from legacy contacts table. Role: child. Child entity from ct_ columns (confidence: 0.70)'