-- Generated by DM Schema Generator
-- Source: contacts (child)
-- Generated: 2026-04-28T20:54:26.270233+00:00

CREATE TABLE ct_record_addresses (
    ct_record_addresse_id     SERIAL PRIMARY KEY,
    ct_record_id              INTEGER,
    address_line1             VARCHAR  -- Source: ct_adr1 — CONTACT-STREET-ADDR-1,
    address_line2             VARCHAR  -- Source: ct_adr2 — CONTACT-STREET-ADDR-2,
    city                      CHAR  -- Source: ct_city — CONTACT-CITY-NAME,
    state                     CHAR  -- Source: ct_st — CONTACT-STATE-CODE,
    zip_code                  CHAR  -- Source: ct_zip — CONTACT-ZIP-CODE,
    mailing_address_line1     VARCHAR  -- Source: ct_madr1 — CONTACT-MAIL-ADDR-1,
    mailing_address_line2     VARCHAR  -- Source: ct_madr2 — CONTACT-MAIL-ADDR-2,
    mailing_city              CHAR  -- Source: ct_mcity — CONTACT-MAIL-CITY,
    mailing_state             CHAR  -- Source: ct_mst — CONTACT-MAIL-STATE,
    mailing_zip_code          CHAR  -- Source: ct_mzip — CONTACT-MAIL-ZIP,
    drivers_license_state     CHAR  -- Source: ct_dlst — CONTACT-DL-STATE,
    marital_status            CHAR  -- Source: ct_mstat — CONTACT-MARITAL-STATUS,
    marital_status            CHAR  -- Source: ct_stat — CONTACT-STATUS-CODE,
    created_at                TIMESTAMPTZ DEFAULT NOW(),
    updated_at                TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_ct_record_addresses_ct_record_id FOREIGN KEY (ct_record_id) REFERENCES ct_records(ct_recid)
);

CREATE INDEX idx_ct_record_addresses_ct_record_id ON ct_record_addresses(ct_record_id);

COMMENT ON TABLE ct_record_addresses IS 'Migrated from legacy contacts table. Role: child. Child entity from ct_ columns (confidence: 0.80)';
