-- Generated by DM Schema Generator
-- Source: contacts (primary)
-- Generated: 2026-04-28T20:54:26.270200+00:00

CREATE TABLE ct_records (
    ct_record_id              SERIAL PRIMARY KEY  -- Primary key for ct_records,
    first_name                CHAR  -- Source: ct_fnam — CONTACT-FIRST-NAME,
    middle_name               CHAR  -- Source: ct_mnam — CONTACT-MIDDLE-NAME,
    last_name                 CHAR  -- Source: ct_lnam — CONTACT-LAST-NAME,
    name_suffix               CHAR  -- Source: ct_sufx — CONTACT-NAME-SUFFIX,
    ssn_hash                  VARCHAR(64)  -- Source: ct_ssn (SHA-256) PII: hash — CONTACT-SSN,
    date_of_birth             CHAR  -- Source: ct_dob — CONTACT-DATE-OF-BIRTH,
    gender                    CHAR  -- Source: ct_gndr — CONTACT-GENDER-CODE,
    ethnicity                 CHAR  -- Source: ct_ethn — CONTACT-ETHNICITY,
    address_type              CHAR  -- Source: ct_adtyp — CONTACT-ADDR-TYPE,
    emergency_contact_name    VARCHAR  -- Source: ct_emrg — CONTACT-EMERGENCY-NAME,
    emergency_contact_relation CHAR  -- Source: ct_erel — CONTACT-EMERGENCY-RELATION,
    drivers_license_number    CHAR  -- Source: ct_dln — CONTACT-DRIVERS-LICENSE-NUM,
    dependents_count          INTEGER  -- Source: ct_dpnds — CONTACT-DEPENDENTS-COUNT,
    language_preference       CHAR  -- Source: ct_lang — CONTACT-LANGUAGE-PREF,
    is_veteran                CHAR  -- Source: ct_vetf — CONTACT-VETERAN-FLAG,
    is_disabled               CHAR  -- Source: ct_disf — CONTACT-DISABILITY-FLAG,
    created_at                CHAR  -- Source: ct_crtdt — CONTACT-CREATED-DATE,
    updated_at                CHAR  -- Source: ct_upddt — CONTACT-UPDATED-DATE,
    source_code               CHAR  -- Source: ct_srccd — CONTACT-SOURCE-CODE,
    fil1                      CHAR  -- Source: ct_fil1 — FILLER-1,
    fil2                      CHAR  -- Source: ct_fil2 — FILLER-2,
    created_at                TIMESTAMPTZ DEFAULT NOW(),
    updated_at                TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_ct_records_ssn_hash ON ct_records(ssn_hash);

COMMENT ON TABLE ct_records IS 'Migrated from legacy contacts table. Role: primary. Primary entity from ct_ columns (confidence: 0.90)';
