-- Generated by DM Schema Generator
-- Source: contacts (child)
-- Generated: 2026-04-28T20:54:26.270246+00:00

CREATE TABLE ct_record_contacts (
    ct_record_contact_id      SERIAL PRIMARY KEY,
    ct_record_id              INTEGER,
    primary_phone             CHAR  -- Source: ct_ptel — CONTACT-PRIMARY-PHONE,
    mobile_phone              CHAR  -- Source: ct_mtel — CONTACT-MOBILE-PHONE,
    work_phone                CHAR  -- Source: ct_wtel — CONTACT-WORK-PHONE,
    email                     VARCHAR  -- Source: ct_emal — CONTACT-EMAIL-ADDR,
    emergency_contact_phone   CHAR  -- Source: ct_etel — CONTACT-EMERGENCY-PHONE,
    created_at                TIMESTAMPTZ DEFAULT NOW(),
    updated_at                TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_ct_record_contacts_ct_record_id FOREIGN KEY (ct_record_id) REFERENCES ct_records(ct_recid)
);

CREATE INDEX idx_ct_record_contacts_ct_record_id ON ct_record_contacts(ct_record_id);

COMMENT ON TABLE ct_record_contacts IS 'Migrated from legacy contacts table. Role: child. Child entity from ct_ columns (confidence: 0.70)';
