-- Transform script: contacts → ct_records
-- Review and customize before execution

INSERT INTO ct_records (
    ct_record_id,
    first_name,
    middle_name,
    last_name,
    name_suffix,
    ssn_hash,
    date_of_birth,
    gender,
    ethnicity,
    address_type,
    emergency_contact_name,
    emergency_contact_relation,
    drivers_license_number,
    dependents_count,
    language_preference,
    is_veteran,
    is_disabled,
    created_at,
    updated_at,
    source_code,
    fil1,
    fil2,
    created_at,
    updated_at
)
SELECT
    ct_recid,
    ct_fnam,
    ct_mnam,
    ct_lnam,
    ct_sufx,
    encode(sha256(ct_ssn::bytea), 'hex'),
    ct_dob,
    ct_gndr,
    ct_ethn,
    ct_adtyp,
    ct_emrg,
    ct_erel,
    ct_dln,
    ct_dpnds,
    ct_lang,
    ct_vetf,
    ct_disf,
    ct_crtdt,
    ct_upddt,
    ct_srccd,
    ct_fil1,
    ct_fil2,
    NOW(),
    NOW()
FROM contacts;
