-- Generated by DM Schema Generator
-- Source: benefit_payments (primary)
-- Generated: 2026-04-24T17:57:04.917485+00:00

CREATE TABLE benefit_payments (
    benefit_payment_id        SERIAL PRIMARY KEY  -- Primary key for benefit_payments,
    claim_id                  INTEGER  -- Source: bp_clmid — PAYMENT-CLAIM-REF,
    paydt                     CHAR  -- Source: bp_paydt — PAYMENT-PROCESS-DATE,
    payment_amount            NUMERIC  -- Source: bp_payam — PAYMENT-AMOUNT,
    methd                     CHAR  -- Source: bp_methd — PAYMENT-METHOD-CODE,
    wkedt                     CHAR  -- Source: bp_wkedt — PAYMENT-WEEK-END-DATE,
    chkno                     CHAR  -- Source: bp_chkno — PAYMENT-CHECK-NUM,
    status                    CHAR  -- Source: bp_stat — PAYMENT-STATUS-CODE,
    created_at                TIMESTAMPTZ DEFAULT NOW(),
    updated_at                TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE benefit_payments IS 'Migrated from legacy benefit_payments table. Role: primary. Primary entity from bp_ columns (confidence: 0.90)';
