-- Generated by DM Schema Generator
-- Source: claims (primary)
-- Generated: 2026-04-24T17:57:04.892278+00:00

CREATE TABLE claims (
    claim_id                  SERIAL PRIMARY KEY  -- Primary key for claims,
    claimant_id               INTEGER  -- Source: cm_clmnt — CLAIM-CLAIMANT-REF,
    employer_id               INTEGER  -- Source: cm_emplr — CLAIM-EMPLOYER-REF,
    seprs                     VARCHAR  -- Source: cm_seprs — CLAIM-SEPARATION-REASON,
    filing_date               CHAR  -- Source: cm_fildt — CLAIM-FILING-DATE,
    benefit_year_end          CHAR  -- Source: cm_byend — CLAIM-BNF-YEAR-END,
    weekly_amount             NUMERIC  -- Source: cm_wkamt — CLAIM-WEEKLY-AMT,
    mxamt                     NUMERIC  -- Source: cm_mxamt — CLAIM-MAX-BNF-AMT,
    totpd                     NUMERIC  -- Source: cm_totpd — CLAIM-TOTAL-PAID,
    wkcnt                     INTEGER  -- Source: cm_wkcnt — CLAIM-WEEKS-COUNT,
    lupdt                     CHAR  -- Source: cm_lupdt — CLAIM-LAST-UPD-DATE,
    benefit_year_start        CHAR  -- Source: cm_bystr — CLAIM-BNF-YEAR-START,
    status                    CHAR  -- Source: cm_stat — CLAIM-STATUS-CODE,
    created_at                TIMESTAMPTZ DEFAULT NOW(),
    updated_at                TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE claims IS 'Migrated from legacy claims table. Role: primary. Primary entity from cm_ columns (confidence: 0.90)';
