-- Generated by DM Schema Generator
-- Source: claimants (primary)
-- Generated: 2026-04-24T17:57:04.841503+00:00

CREATE TABLE claimants (
    claimant_id               SERIAL PRIMARY KEY  -- Primary key for claimants,
    first_name                CHAR  -- Source: cl_fnam — CLAIMANT-FIRST-NAME,
    last_name                 CHAR  -- Source: cl_lnam — CLAIMANT-LAST-NAME,
    ssn                       CHAR  -- Source: cl_ssn — CLAIMANT-SSN,
    date_of_birth             CHAR  -- Source: cl_dob — CLAIMANT-DATE-OF-BIRTH,
    bank_account              CHAR  -- Source: cl_bact — CLAIMANT-BANK-ACCT,
    bank_routing              CHAR  -- Source: cl_brtn — CLAIMANT-BANK-ROUTE,
    registered_at             CHAR  -- Source: cl_rgdt — CLAIMANT-REG-DATE,
    is_deceased               CHAR  -- Source: cl_dcsd — CLAIMANT-DECEASED-FLAG,
    fil1                      CHAR  -- Source: cl_fil1 — FILLER,
    phone_number              CHAR  -- Source: cl_phon — CLAIMANT-PHONE-NUM,
    email                     VARCHAR  -- Source: cl_emal — CLAIMANT-EMAIL-ADDR,
    created_at                TIMESTAMPTZ DEFAULT NOW(),
    updated_at                TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE claimants IS 'Migrated from legacy claimants table. Role: primary. Primary entity from cl_ columns (confidence: 0.90)';
