-- Generated by DM Schema Generator
-- Source: claimants (child)
-- Generated: 2026-04-24T17:57:04.841527+00:00

CREATE TABLE claimant_addresses (
    claimant_addresse_id      SERIAL PRIMARY KEY,
    claimant_id               INTEGER,
    address_line1             VARCHAR  -- Source: cl_adr1 — CLAIMANT-STREET-ADDR,
    city                      CHAR  -- Source: cl_city — CLAIMANT-CITY-NAME,
    state                     CHAR  -- Source: cl_st — CLAIMANT-STATE-CODE,
    zip_code                  CHAR  -- Source: cl_zip — CLAIMANT-ZIP-CODE,
    status                    CHAR  -- Source: cl_stat — CLAIMANT-STATUS-CODE,
    created_at                TIMESTAMPTZ DEFAULT NOW(),
    updated_at                TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_claimant_addresses_claimant_id FOREIGN KEY (claimant_id) REFERENCES claimants(cl_recid)
);

CREATE INDEX idx_claimant_addresses_claimant_id ON claimant_addresses(claimant_id);

COMMENT ON TABLE claimant_addresses IS 'Migrated from legacy claimants table. Role: child. Child entity from cl_ columns (confidence: 0.80)';
