-- Generated by DM Schema Generator
-- Source: employers (primary)
-- Generated: 2026-04-24T17:57:04.868018+00:00

CREATE TABLE employers (
    employer_id               SERIAL PRIMARY KEY  -- Primary key for employers,
    name                      VARCHAR  -- Source: er_name — EMPLOYER-CORP-NAME,
    ein                       CHAR  -- Source: er_ein — EMPLOYER-EIN,
    indicator                 CHAR  -- Source: er_ind — EMPLOYER-INDUSTRY-CODE,
    phone_number              CHAR  -- Source: er_phon — EMPLOYER-PHONE-NUM,
    created_at                TIMESTAMPTZ DEFAULT NOW(),
    updated_at                TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE employers IS 'Migrated from legacy employers table. Role: primary. Primary entity from er_ columns (confidence: 0.90)';
