-- Generated by DM Schema Generator
-- Source: employers (child)
-- Generated: 2026-04-24T17:57:04.868036+00:00

CREATE TABLE employer_addresses (
    employer_addresse_id      SERIAL PRIMARY KEY,
    employer_id               INTEGER,
    address_line1             VARCHAR  -- Source: er_adr1 — EMPLOYER-STREET-ADDR,
    city                      CHAR  -- Source: er_city — EMPLOYER-CITY-NAME,
    state                     CHAR  -- Source: er_st — EMPLOYER-STATE-CODE,
    zip_code                  CHAR  -- Source: er_zip — EMPLOYER-ZIP-CODE,
    status                    CHAR  -- Source: er_stat — EMPLOYER-STATUS-CODE,
    created_at                TIMESTAMPTZ DEFAULT NOW(),
    updated_at                TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_employer_addresses_employer_id FOREIGN KEY (employer_id) REFERENCES employers(er_recid)
);

CREATE INDEX idx_employer_addresses_employer_id ON employer_addresses(employer_id);

COMMENT ON TABLE employer_addresses IS 'Migrated from legacy employers table. Role: child. Child entity from er_ columns (confidence: 0.80)';
